apiVersion: batch/v1
kind: Job
metadata:
  name: load-100
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: locust
          image: locustio/locust:latest
          imagePullPolicy: IfNotPresent
          command: ["locust"]
          args:
            - -f
            - /mnt/locust/locustfile.py
            - --host=http://gateway:8080
            - --headless
            - -u
            - "100"                       # ← users
            - -r
            - "2"                         # ← ramp-up /s
            - -t
            - "60s"
            - --only-summary
          volumeMounts:
            - { name: locustfile, mountPath: /mnt/locust }
      volumes:
        - name: locustfile
          configMap: { name: locustfile }
